[taxonomies]
tags = "tags"

[params]
theme = 'hugo-texify2'
title="Armas.AI ğŸ‘¨ğŸ½â€ğŸ’»ğŸ‡²ğŸ‡½"
description = "Come visit and learn with me new topics in Engineering and Artificial Intelligence!"
images = ['images/site/favicon/website_icon.jpg']
footnote = """
  Follow me on <a class=link href=https://github.com/alejandroarmas target=_blank rel=noopener>GitHub</a>,
  <a class=link href=https://www.linkedin.com/in/armasalejandro/ target=_blank rel=noopener>LinkedIn</a> or
  <a class=link href=/index.xml>RSS</a> |
  <a class=link href=https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en target=_blank rel=noopener>CC BY-NC-SA 4.0</a>
"""
keywords = ["machine learning", "artificial intelligence", "ai", "ml", "probability", "programming", "software engineering", "machine learning engineering"]
custom_css = []
customJS = []
dateFormat = "January 2, 2006"
emphasisWithDots = false
since = "2019"
toc = true
showWordCount = true
showReadingTime = true
rootFontSize = "120%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = false


[module]
[[module.imports]]
  path = 'github.com/hugomods/katex'

[[menu.main]]
identifier = "post"
name = "Posts"
url = "/"
weight = 1

[[menu.main]]
identifier = "archives"
name = "Archive"
url = "/post/"
weight = 2


[[menu.main]]
identifier = "coaching"
name = "Coaching"
url = "/consulting/"
weight = 3

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 4

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume/"
weight = 5

[params.sharingbuttons]
facebook = false
twitter = false
email = true
linkedin = true
reddit = true
whatsapp = false
hackernews = true
telegram = false

[params.commentEngine]
code = """
"""

[params.buymeacoffee]
code = """
"""